server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /minnongApi/

####数据源配置####
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.248:3306/minnong?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: edwin
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1

#####设置MultipartFile文件上传大小####
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

#####添加热部署#####
  devtools:
    remote:
      restart:
        enabled: true

####redis配置####
  redis:
    host: 192.168.0.153
    port: 6379
    password:

#### 邮件配置####
  mail:
    host: smtp.qq.com
    username: 1815066657@qq.com
    password: ivldcisqgynndjca
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true　

####mybatis配置####
mybatis:
  type-aliases-package: com.mx.minnong.pojo
  mapper-locations: classpath:mapper/*.xml

####通用mapper配置####
mapper:
  not-empty: false
  identity: MYSQL
####分页插件####
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
  - 192.168.0.156:22122